### ISSUE TITLE
Just logged in as pretend user

### ISSUE THREAD

**Issue by glenngoss** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#1]
This is what I see on log in.

![image](https://user-images.githubusercontent.com/21148346/64911939-b42dbb80-d6ed-11e9-85ec-59367074041d.png)

Is this just me?  You fixed this for my exec.sec log in. 

![image](https://user-images.githubusercontent.com/21148346/64911961-e93a0e00-d6ed-11e9-8f7d-15c6a1524be2.png)

is any one else going to be confused?

**Comment by brunofvalli** [comment]
Yes, you are the president of the Chapter of UTA.

ONce you log off (and do remember to log off your record will be removed. If you were to try to add a new member you will see you are only able to add members to UTA.

BTW you are adding this ticket in the CHiEpsilonMemberSupport github page instead of the ChiEpsilon page.
