### ISSUE TITLE
Moving Initiates from Officer Approved to Paid and Scheduled. 

### ISSUE THREAD

**Issue by skab16** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#14]
**What is the e-mail address you are using to login to xehub**
skab16@gatech.edu

**Describe the bug**
Hello, 
I'm trying to move the applicants under officer approved all the way to scheduled, however I keep getting a server error when I click "Pay" in the Officer Approved Tab. 

**To Reproduce**
1. Go to Applicants
2. Click on Officer Approved
3. Scroll down to either of the people listed (Emma Axelson, or Ronak Lakhani)
4. Click on Pay
5. See Error

**Expected behavior**
Last week, I was able to move through the pages easily with other applicants. Even today I was able to go through the pages from paid to scheduled for Ryan Foster. However, when I clicked on these two applicants, this error occurred. This is not the first time this happened. I went through the same motions last Thursday, and this error occurred for the last three applicants, including Emma Axelson and Ronak Lakhani. I decided to check back on it today, and I was able to move Ryan Foster easily (the error popped up for him last week as well). However, Emma and Ronak still have the same issues as last Thursday. 

**Screenshots**
If applicable, add screenshots to help explain your problem. (You can press Ctrl+Windows+S to take a screen shot and paste right here with Ctrl+V)
![image](https://user-images.githubusercontent.com/56938708/68597102-6245af80-046a-11ea-825d-1ee9aecb9000.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS Catalina, version 10.15.1
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Chrome Version 78.0.3904.87 

**Smartphone (please complete the following information):** N/A

**Additional context**

**Comment by brunofvalli** [comment]
Found the issue. I have fixed this and will be online shortly.

You will get the following message now instead of the crash message:
![image](https://user-images.githubusercontent.com/5949285/68637870-82ef2300-04c5-11ea-9d41-58b1d2b1f08f.png)

When you click on the person normally it is trying to find the order for the person. There was a previous error that a person order was not getting created correctly. The system will now re-route you back to the Approval Screen where you need to just click on "Approve"
![image](https://user-images.githubusercontent.com/5949285/68637923-a7e39600-04c5-11ea-97b4-06fc6199f236.png)

**Comment by brunofvalli** [comment]
This has been fixed. Please try to do again. If there still an issue please make a note on this issue and I will reopen it.
