### ISSUE TITLE
Cannot register

### ISSUE THREAD

**Issue by bgrennie17** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#18]
I tried to register using my school email and thought I did not receive an email, so I tried my personal and did not receive one again.  I didn't realize it was in my spam till the next day and when I clicked the link in my email I got an error message.  Here's the snip.

![errorXEhubLink](https://user-images.githubusercontent.com/57878209/69015681-583d1880-0964-11ea-9bed-c323c69cce5a.JPG)

I wasn't sure if it timed out somehow, so I tried one more time with my school email to click the link right away.  But when I tried to register again it said my name was already taken and it did not resend the link.  Here's that snip.

![errorXEhubLink3](https://user-images.githubusercontent.com/57878209/69015840-773caa00-0966-11ea-809d-bf72adbb1793.JPG)

 Then I tried logging in to see if it was somehow still verified anyway, but it tells me to confirm my email.  Here's that message.

![errorXEhubLink2](https://user-images.githubusercontent.com/57878209/69015718-e31e1300-0964-11ea-8735-fe6ea6b17898.JPG)

Not sure what to do now, I can't get in and I need that verification link to work.  Here's my info:

full name: Brian Rennie
e-mail addresses (if you have more than one): rennieb1@tcnj.edu and bgrennie17@gmail.com
The e-mail address you used to sign in: cannot
officer position: President
chapter name: The College of New Jersey (143)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 78

**Comment by brunofvalli** [comment]
@glenngoss 
I need you to please verify that Brian Rennie is supposed to be the president of Chapter 143 "The College Of New Jersey"  I cannot verify that since the current Officers that I show are the following:
![image](https://user-images.githubusercontent.com/5949285/69115980-31f4a700-0a50-11ea-96cc-83f688d41932.png)

Once you confirm I can add him

@bgrennie17 
I have connect your account. I noticed you have not verified your e-mail. You can re-send the confirmation e-mail by clicking on this link:
![image](https://user-images.githubusercontent.com/5949285/69116028-69635380-0a50-11ea-92f4-41af67442bdf.png)

Check your Spam folder for an confirmation e-mail coming from ChiEpsilon@gmail.com

**Comment by bgrennie17** [comment]
Ah thank you! Sorry that was dumb on my part.  Now it's not allowing me to save my account, though, because  it's saying my emails are duplicates.

![errorXEhub4](https://user-images.githubusercontent.com/57878209/69209730-5ae76b80-0b26-11ea-88a6-aac84dac8530.JPG)

**Comment by brunofvalli** [comment]
I have fixed this. If you login again it should associate you with the right account.
