### ISSUE TITLE
Membership Initiation Fees

### ISSUE THREAD

**Issue by jonak1** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#23]
When I originally planned for new initiates, I looked on the website at the fee schedule and there was an option that was less if you did not select jewelry. I set up initiation costs based on the understanding that it would only cost $78/person. Is there any way to change the charges for each student?

**Comment by brunofvalli** [comment]
that would be a @glenngoss question. The system currently does not allow the removal of items from an initiation.

**Comment by glenngoss** [comment]
The system is currently set-up to mimic the majority of the cash transactions between candidates and their respective chapters.     **Since you are collecting the lower, non-jewelry, fee, I'd recommend inputting $94.00 to keep the system happy and to move your candidates along the flow-path between invitation to attended.** 

Eventually, we plan to integrate the XEHub system with our accounting system.  That way you will receive your invoices automatically without having to wait for someone in HQ to generate an invoice and send it to you.   We are a long way from having this part of the build included in the XEHub system.

In the future, we also hope to allow individual chapters to input cost items not related to Society initiation fees.  This will allow you to keep track of all money received from the candidates and members too.

**Comment by jonak1** [comment]
So to clarify, I am being charged for the higher, jewelry included, fee?

**Comment by glenngoss** [comment]
Technically, that is correct.  However, HQ is still not receiving vendor information from the system.  Once you schedule all candidates to a specific initiation event, send us an email (XEHQ@chi-epsilon.org) telling us the date of your initiation, a list of candidates to be initiated, their membership type (U, G, FM, or CHM) and that you do not want to order jewelry.  We'll take care of sending you the correct invoice.  Once paid, we will order Certificates for your event.   After you finish taking roll following the event, let us know who was present or not present. At that time we'll order wallet cards for each of your new members.  Don't forget to update the Hub at the same time.

**Comment by brunofvalli** [comment]
@glenngoss 
I have just added version 1.15.19349.2210 and now values on an order can be changed only by the admin.
