### ISSUE TITLE
Four students cannot accept pledge invitation

### ISSUE THREAD

**Issue by SRhatican** [MBFVSolutionsLLC/ChiEpsilonMemberSupport#63]
Hello, 

On Wednesday, September 22nd, The College of New Jersey's Chi Epsilon chapter invited seven students to pledge. All seven payed, were input into the system and had the invitation emails sent out to them. Four of these students, Hayley Conway, Jack Lacina, Connor Conyngham and Anthony Cooper have been unable to open the link provided in the invitation email. Whenever they clicked on the link it brought them to a window which said 'server error'. The other three were only able to open the link and accept the invitation by copying the link and pasting it into a new browser window. Is there anything that they can do to accept the invitation, or are you guys able to do it manually from your end? Any help would be greatly appreciated.

Thank you
Sean Rhatican, Vice President - Chapter 143

**Comment by brunofvalli** [comment]
Copying and pasting the link into Chrome should solve their issue.
Could you forward me the e-mail these students are receiving from the system?
I have gotten the e-mail sent to Hayley and the link seems to work fine.
Could you please answer the following questions:
- What OS is any of these users using (Windows 10, iPhone, OSX, Android, ChromeOS)?
- What application are they using to check their e-mail (GMail, Outlook, Chrome, Safari, Edge, Internet Explorer)?
- What browser are they using to reach the XEHub site? (Chrome, Safari, Edge, Firefox, Internet Explorer, etc...)

We cannot manually move them forward since they would not have access to their account to continue forward with the process.

**Comment by brunofvalli** [comment]
I need more information to be able to help you. Please answer the questions above.

**Comment by SRhatican** [comment]
Hello Bruno! My apologies for the late response. We were able to get three of the four to accept the invitation using my computer but the fourth, Connor Conyngham, still wasn't able to accept the invitation. He said that he had previously attempted to accept the invitation and had filled it out, but it's not showing up for us. I was wondering if you would be able to check the status of Connor's invitation. If he still hasn't been able to do it, is there a way that the invitation can be resent? Thank you for your help.

**Comment by brunofvalli** [comment]
Sorry for my long delay.

I see you have Connor schedule for initiation on 12/11/2021

https://xehub.azurewebsites.net/Event/Scheduled/609be0b5-c0cc-455f-ad6d-bc94075b723f

Is that correct, so I assume you got it all resolved. 

I am closing this issue.
